apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-nginx-proxy-mgr
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-nginx-proxy-mgr
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-nginx-proxy-mgr
    spec:
      containers:
      - image: jc21/nginx-proxy-manager:latest
        imagePullPolicy: Always
        name: nginx-proxy-mgr
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 81
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /etc/letsencrypt
          name: letsencrypt
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: data
      - emptyDir: {}
        name: letsencrypt
