apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.1.2"],"port":30080,"protocol":"TCP","serviceName":"default:nginx-proxy-mgr","allNodes":true},{"addresses":["192.168.1.2"],"port":30443,"protocol":"TCP","serviceName":"default:nginx-proxy-mgr","allNodes":true},{"addresses":["192.168.1.2"],"port":30081,"protocol":"TCP","serviceName":"default:nginx-proxy-mgr","allNodes":true}]'
  creationTimestamp: "2022-11-26T03:12:30Z"
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-nginx-proxy-mgr
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/publicEndpoints: {}
        f:labels:
          .: {}
          f:workload.user.cattle.io/workloadselector: {}
      f:spec:
        f:clusterIP: {}
        f:clusterIPs: {}
        f:externalTrafficPolicy: {}
        f:internalTrafficPolicy: {}
        f:ipFamilies: {}
        f:ipFamilyPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:nodePort: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":81,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:nodePort: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":443,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:nodePort: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: agent
    operation: Update
    time: "2022-11-26T03:12:30Z"
  name: nginx-proxy-mgr
  namespace: default
  resourceVersion: "9692"
  uid: a0fee997-49a9-4ef7-b2e0-d4233cc2bd08
spec:
  clusterIP: 10.43.161.7
  clusterIPs:
  - 10.43.161.7
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 30443
    port: 443
    protocol: TCP
    targetPort: 443
  - name: admin
    nodePort: 30081
    port: 81
    protocol: TCP
    targetPort: 81
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-nginx-proxy-mgr
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
