apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  project: default
  source:
    path: cluster/external-secrets
    repoURL: 'https://github.com/thonyprice/homelab'
    targetRevision: HEAD
  destination:
    namespace: external-secrets
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
