apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-pihole
spec:
  project: default
  source:
    path: cluster/external-dns-pihole
    repoURL: 'https://github.com/thonyprice/homelab'
    targetRevision: HEAD
  destination:
    namespace: pihole-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
