apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- argocd.yaml
- argocd-apps.yaml
- external-dns-pihole.yaml
- ingress-nginx.yaml
- kyverno.yaml
- longhorn.yaml
- metallb.yaml
- nginx-example.yaml
- pihole.yaml
