# Ref: https://kyverno.io/docs/installation/platform-notes/#notes-for-argocd-users
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default
  sources:
    - chart: kyverno
      repoURL: https://kyverno.github.io/kyverno
      targetRevision: v3.2.7
      helm:
        values: |
          crds:
            migration:
              enabled: false
    - repoURL: 'https://github.com/thonyprice/homelab'
      path: cluster/kyverno
      targetRevision: HEAD
  destination:
    namespace: kyverno
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
