# Ref: https://kyverno.io/docs/installation/platform-notes/#notes-for-argocd-users
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default
  sources:
    - chart: kyverno
      repoURL: https://kyverno.github.io/kyverno
      targetRevision: v3.2.7
      helm:
        values: |
          crds:
            migration:
              enabled: false
    - repoURL: 'https://github.com/thonyprice/homelab'
      path: cluster/kyverno
      targetRevision: HEAD
  ignoreDifferences:
    - group: "batch"
      kind: "CronJob"
      jqPathExpressions:
        - .spec.jobTemplate.spec.template.spec.containers[] | select(.name == "cleanup")
    - group: "kyverno.io"
      kind: "ClusterPolicy"
      jqPathExpressions:
        - .spec.rules[] | select(.name == "add-env-vars")
  destination:
    namespace: kyverno
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # INFO: Special sync options due to bug, see https://github.com/kyverno/kyverno/issues/10283
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
