apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.7.2 
      helm:
        values: |
          preUpgradeChecker:
            # Setting that allows Longhorn to perform pre-upgrade checks. Disable this setting when installing Longhorn using Argo CD or other GitOps solutions.
            jobEnabled: false
          ingress:
            enabled: true
            host: longhorn.home
            ingressClassName: nginx-internal
    - repoURL: 'https://github.com/thonyprice/homelab'
      path: cluster/longhorn
      targetRevision: HEAD
  destination:
    namespace: longhorn-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
