apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.7.2 
      helm:
        values: |
          defaultSettings:
            # Default number of replicas for volumes created using the Longhorn UI
            defaultReplicaCount: 2
          persistence:
            # Replica count of the default Longhorn StorageClass.
            defaultClassReplicaCount: 2
          preUpgradeChecker:
            # Setting that allows Longhorn to perform pre-upgrade checks. Disable this setting when installing Longhorn using Argo CD or other GitOps solutions.
            jobEnabled: false
          ingress:
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-staging
            enabled: true
            host: longhorn.fm92.org
            ingressClassName: nginx-internal
            tls: true
            tlsSecret: longhorn-tls
          service:
            ui:
              type: LoadBalancer
              # No need for a nodePort for LoadBalancer but the chart will define
              # a nodePort either way so not setting it yields an argocd diff
              nodePort: 32216
    - repoURL: 'https://github.com/thonyprice/homelab'
      path: cluster/longhorn
      targetRevision: HEAD
  destination:
    namespace: longhorn-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
