apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    path: cluster/longhorn
    repoURL: 'https://github.com/thonyprice/homelab'
    targetRevision: HEAD
  destination:
    namespace: longhorn-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.7.2
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
