apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  project: default
  source:
    path: cluster/metallb
    repoURL: 'https://github.com/thonyprice/homelab'
    targetRevision: HEAD
  destination:
    namespace: metallb-system
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: addresspools.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
