apiVersion: v1
kind: Secret
metadata:
  name: gcpsm-secret
  namespace: external-secret
  labels:
    type: gcpsm
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
  secret-access-credentials: |-
    {
      "data": "paste-from-generated-sa-key"
    }
