# TODO: Install external secrets service to pull
# secret values into cluster. In the mean time,
# set the correct secret value and apply manifest manually.
# kubectl apply -f pihole-secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: pihole-password
  namespace: pihole-system
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
data:
  EXTERNAL_DNS_PIHOLE_PASSWORD=***
---
