---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pihole-password
  namespace: pihole-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: pihole-password
    creationPolicy: Owner
  data:
  - secretKey: EXTERNAL_DNS_PIHOLE_PASSWORD
    remoteRef:
      key: pihole-admin-password
