pihole:
  DNS1: # Upstream DNS server IP
    192.168.1.1

  persistentVolumeClaim:
    enabled: true

  ingress:
    enabled: true
    hosts:
      - "pihole.home"

  admin:
    existingSecret: pihole-password

  serviceWeb:
    loadBalancerIP: 192.168.1.99
    annotations:
      metallb.universe.tf/allow-shared-ip: pihole-svc
    type: LoadBalancer

  serviceDns:
    loadBalancerIP: 192.168.1.99
    annotations:
      metallb.universe.tf/allow-shared-ip: pihole-svc
    type: LoadBalancer

  replicaCount: 1
