---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  TIMEZONE: "Europe/Stockholm"
  SVC_NGINX_ADDR: "192.168.69.101"
  SVC_JELLYFIN_ADDR: "192.168.2.50"
  SVC_K8S_GATEWAY_ADDR: "192.168.2.222"
