apiVersion: v1
kind: Secret
metadata:
  name: gcpsm-secret
  namespace: external-secrets
  labels:
    type: gcpsm
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
  # See https://external-secrets.io/latest/provider/google-secrets-manager/#gcp-service-account-authentication
  secret-access-credentials: |-
